- name: Access Test for All Hosts
  hosts: all
  gather_facts: no

  tasks:

    - name: Ping (basic connectivity)
      ansible.builtin.ping:

    - name: Show ansible_user (user used for SSH)
      ansible.builtin.debug:
        var: ansible_user

    - name: Check id (with sudo)
      become: yes
      ansible.builtin.command: id -u
      register: sudo_id

    - name: Print sudo ID (should be 0 = root)
      ansible.builtin.debug:
        msg: "sudo uid = {{ sudo_id.stdout }}"

    - name: Check whoami (with sudo)
      become: yes
      ansible.builtin.command: whoami
      register: whoami_sudo

    - name: Print whoami (with sudo)
      ansible.builtin.debug:
        msg: "whoami (sudo) = {{ whoami_sudo.stdout }}"

    - name: Test sudo permission (run true)
      become: yes
      ansible.builtin.command: "true"
      register: sudo_test
      changed_when: false

    - name: Print sudo test result
      ansible.builtin.debug:
        msg: "sudo OK"

    - name: Show hostname
      ansible.builtin.command: hostname
      register: hostn

    - name: Print hostname
      ansible.builtin.debug:
        msg: "hostname = {{ hostn.stdout }}"
