- name: Check access to all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Ping (basic connectivity)
      ansible.builtin.ping:

    - name: Show ansible_user (user ที่ Ansible ใช้ ssh)
      ansible.builtin.debug:
        var: ansible_user

    - name: Check whoami without sudo
      ansible.builtin.command: whoami
      register: whoami_no_sudo

    - name: Print whoami without sudo
      ansible.builtin.debug:
        msg: "whoami (no sudo) = {{ whoami_no_sudo.stdout }}"

    - name: Check whoami with sudo (become)
      become: yes
      ansible.builtin.command: whoami
      register: whoami_sudo

    - name: Print whoami with sudo
      ansible.builtin.debug:
        msg: "whoami (sudo) = {{ whoami_sudo.stdout }}"

    - name: Test simple sudo command
      become: yes
      ansible.builtin.command: true
      register: sudo_test
      changed_when: false

    - name: Show sudo test result
      ansible.builtin.debug:
        msg: "sudo OK"
