---
- name: Install RealVNC Server (Simulation)
  hosts: all
  become: yes
  tasks:
    - name: Download RealVNC Server Package
      get_url:
        # ลิงก์นี้เป็นเวอร์ชันล่าสุด ณ ปัจจุบัน (7.x)
        url: https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.10.0-Linux-x64.deb
        dest: /tmp/realvnc-server.deb
        mode: '0644'

    - name: Install RealVNC from .deb
      apt:
        deb: /tmp/realvnc-server.deb
        state: present
        update_cache: yes
      ignore_errors: yes 
      # ignore_errors: ใส่เผื่อไว้กรณี Dependency มีปัญหา แต่อยากให้จบ Task
