---
- name: Install RealVNC Server (Simulation)
  hosts: all
  become: yes
  # --- ส่วนที่เพิ่มเข้ามา ---

  # -----------------------
  
  tasks:
    - name: Download RealVNC Server Package
      get_url:
        url: https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.10.0-Linux-x64.deb
        dest: /tmp/realvnc-server.deb
        mode: '0644'

    - name: Install RealVNC from .deb
      apt:
        deb: /tmp/realvnc-server.deb
        state: present
        update_cache: yes
      # ลบ ignore_errors ออกครับ เราอยากเห็น Error จริงถ้ามันพัง
