---
- name: Uninstall RealVNC (Clean Output)
  hosts: all
  become: yes

  tasks:
    # 1. หยุด Service
    - name: Stop VNC Service
      service:
        name: vncserver-x11-serviced
        state: stopped
        enabled: no
      ignore_errors: yes
      register: stop_result

    # แสดงผลเฉพาะชื่อและสถานะ
    - name: Show Service Status
      debug:
        msg: 
          - "Service: {{ stop_result.name }}"
          - "State: {{ stop_result.state }}"
          - "Stopped Success: {{ stop_result.changed }}"

    # 2. ลบโปรแกรม
    - name: Purge VNC Package
      apt:
        name: realvnc-vnc-server
        state: absent
        purge: yes
        autoremove: yes
      register: purge_result

    # แสดงผลสั้นๆ ว่าลบแล้วหรือยัง
    - name: Show Uninstall Status
      debug:
        msg: "Package Removed: {{ purge_result.changed }}"

    # 3. ตรวจสอบครั้งสุดท้าย (หา Process ที่เกี่ยวกับ vnc)
    - name: Check for Running VNC Processes
      shell: ps -ef | grep [v]nc || true
      register: vnc_ps_check
      changed_when: false

    # แสดงผลเฉพาะบรรทัดที่มีคำว่า vnc (ถ้าว่างแปลว่าเกลี้ยง)
    - name: Final VNC Process Check
      debug:
        msg: 
          - "Remaining VNC Processes:"
          - "{{ vnc_ps_check.stdout_lines | default('None (Clean)') }}"
