---
- name: Uninstall RealVNC (Clean Output)
  hosts: all
  become: yes

  tasks:
    # 1. หยุด Service
    - name: Stop VNC Service
      service:
        name: vncserver-x11-serviced
        state: stopped
        enabled: no
      ignore_errors: yes
      register: stop_result

    # แสดงผลเฉพาะชื่อและสถานะ
    - name: Show Service Status
      debug:
        msg: 
          - "Service: {{ stop_result.name }}"
          - "State: {{ stop_result.state }}"
          - "Stopped Success: {{ stop_result.changed }}"

    # 2. ลบโปรแกรม
    - name: Purge VNC Package
      apt:
        name: realvnc-vnc-server
        state: absent
        purge: yes
        autoremove: yes
      register: purge_result

    # แสดงผลสั้นๆ ว่าลบแล้วหรือยัง
    - name: Show Uninstall Status
      debug:
        msg: "Package Removed: {{ purge_result.changed }}"

# 3. ตรวจสอบครั้งสุดท้าย (เฉพาะ Process ของ RealVNC จริงๆ)
    - name: Check for RealVNC Binaries
      # หาเฉพาะ process ที่ชื่อ vncserver-x11 และตัด grep/ansible ออก
      shell: ps -ef | grep "vncserver-x11" | grep -v grep | grep -v ansible || true
      register: vnc_ps_check
      changed_when: false

    - name: Final VNC Process Check
      debug:
        msg: 
          - "RealVNC Processes Remaining:"
          - "{{ vnc_ps_check.stdout_lines | default('NONE (System is Clean) ✅') }}"
