---
- name: Completely Remove RealVNC Server (With Detailed Logs)
  hosts: all
  become: yes

  tasks:
    # ---------------------------------------------------------
    # 1. หยุด Service
    # ---------------------------------------------------------
    - name: Stop and Disable RealVNC Service
      service:
        name: vncserver-x11-serviced
        state: stopped
        enabled: no
      ignore_errors: yes
      register: service_stop_result  # <--- เก็บผลลัพธ์ไว้

    - name: Show Stop Service Result
      debug:
        var: service_stop_result     # <--- แสดงผลลัพธ์ออกมา

    # ---------------------------------------------------------
    # 2. ลบโปรแกรม (Purge)
    # ---------------------------------------------------------
    - name: Purge RealVNC Package
      apt:
        name: realvnc-vnc-server
        state: absent
        purge: yes
        autoremove: yes
      register: apt_remove_result    # <--- เก็บผลลัพธ์ไว้

    - name: Show Apt Remove Result
      debug:
        # แสดงเฉพาะ stdout (ข้อความที่ apt พ่นออกมา) เพื่อให้อ่านง่าย
        # หรือถ้าไม่มี stdout ให้แสดง msg (กรณี apt module ไม่คืน text)
        msg: 
          - "{{ apt_remove_result.stdout_lines | default('No standard output') }}"
          - "State Changed: {{ apt_remove_result.changed }}"

    # ---------------------------------------------------------
    # 3. ลบไฟล์ติดตั้ง
    # ---------------------------------------------------------
    - name: Remove Installer File
      file:
        path: /tmp/realvnc-server.deb
        state: absent
      register: file_remove_result   # <--- เก็บผลลัพธ์ไว้

    - name: Show File Removal Result
      debug:
        var: file_remove_result

    # ---------------------------------------------------------
    # 4. ตรวจสอบความแน่ใจ (Verify)
    # ---------------------------------------------------------
    - name: Verify Removal
      shell: systemctl status vncserver-x11-serviced
      register: service_check
      failed_when: service_check.rc == 0
      ignore_errors: yes

    - name: Show Final Verification
      debug:
        msg: 
          - "Service Found Status (RC): {{ service_check.rc }}"
          - "Note: If RC is NOT 0, it means the service is successfully GONE."
          - "{{ service_check.stderr_lines }}"
