---
- name: Completely Remove RealVNC Server
  hosts: all
  become: yes

  tasks:
    # 1. หยุดและปิดการทำงานของ Service ก่อน (สำคัญมาก)
    - name: Stop and Disable RealVNC Service
      service:
        name: vncserver-x11-serviced
        state: stopped
        enabled: no
      ignore_errors: yes  # ใส่เผื่อไว้ กรณีที่โปรแกรมอาจจะไม่อยู่แล้ว จะได้ไม่ Error

    # 2. ลบโปรแกรมพร้อมไฟล์ Config (Purge)
    - name: Purge RealVNC Package
      apt:
        name: realvnc-vnc-server
        state: absent
        purge: yes       # ลบไฟล์ Config ที่ตกค้างด้วย
        autoremove: yes  # ลบ dependencies ที่ไม่ได้ใช้แล้ว

    # 3. ลบไฟล์ติดตั้ง .deb ที่โหลดมาทิ้งไว้ใน /tmp
    - name: Remove Installer File
      file:
        path: /tmp/realvnc-server.deb
        state: absent

    # 4. (Optional) ตรวจสอบความแน่ใจว่า Service หายไปจริง
    - name: Verify Removal
      shell: systemctl status vncserver-x11-serviced
      register: service_check
      failed_when: service_check.rc == 0  # ถ้า Command สำเร็จ (เจอ Service) แปลว่าลบไม่หมด ให้ฟ้อง Error
      ignore_errors: yes # ปกติ systemctl status จะ error ถ้าไม่เจอ service ซึ่งคือสิ่งที่เราต้องการ

    - name: Show Removal Result
      debug:
        msg: "RealVNC has been successfully removed."
      when: service_check.rc != 0 # แสดงข้อความเมื่อหา Service ไม่เจอแล้ว
